/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'coucoun' at '12/03/17 23:18' with Gradle 2.1
 *
 * @author coucoun, @date 12/03/17 23:18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
